[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[workspace]
members = ["src-tauri", "dnas/*/zomes/coordinator/*", "dnas/*/zomes/integrity/*"]
resolver = "2"

[workspace.dependencies]
hdi = "0.4.1-rc"
hdk = "0.3.1-rc"
serde = "1.0.197"

[workspace.dependencies.holochain]
default-features = false
features = ["test_utils"]
version = "0.3.1-rc"

[workspace.dependencies.households]
path = "dnas/plenty/zomes/coordinator/households"

[workspace.dependencies.households_integrity]
path = "dnas/plenty/zomes/integrity/households"

[patch.crates-io]
holochain = { git = "https://github.com/guillemcordoba/holochain", branch = "develop-0.3" }
holochain_nonce = { git = "https://github.com/guillemcordoba/holochain", branch = "develop-0.3" }
holochain_types = { git = "https://github.com/guillemcordoba/holochain", branch = "develop-0.3" }
holochain_zome_types = { git = "https://github.com/guillemcordoba/holochain", branch = "develop-0.3" }
holochain_integrity_types = { git = "https://github.com/guillemcordoba/holochain", branch = "develop-0.3" }
holochain_keystore = { git = "https://github.com/guillemcordoba/holochain", branch = "develop-0.3" }
holo_hash = { git = "https://github.com/guillemcordoba/holochain", branch = "develop-0.3" }
kitsune_p2p_timestamp = { git = "https://github.com/guillemcordoba/holochain", branch = "develop-0.3" }
holochain_conductor_api = { git = "https://github.com/guillemcordoba/holochain", branch = "develop-0.3" }
mr_bundle = { git = "https://github.com/guillemcordoba/holochain", branch = "develop-0.3" }
